# Generated by Django 6.0.4 on 2026-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_processo_criado_em_alter_amostracontinua_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='usar_regras_western',
            field=models.BooleanField(default=False, help_text='Ativa a verificação das Regras do Western Electric Handbook'),
        ),
    ]
