# Generated by Django 6.0.4 on 2026-04-29 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_carta', models.CharField(choices=[('XR', 'X-R'), ('IMR', 'I-MR'), ('P', 'P'), ('U', 'U')], max_length=3)),
                ('lse', models.FloatField(blank=True, help_text='Limite Superior de Especificação', null=True)),
                ('lie', models.FloatField(blank=True, help_text='Limite Inferior de Especificação', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmostraContinua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores', models.JSONField(help_text='Lista de medições numéricas')),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Amostras_continuas', to='app.processo')),
            ],
        ),
        migrations.CreateModel(
            name='AmostraAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_amostra', models.PositiveIntegerField(help_text='Tamanho do lote/subgrupo (n)')),
                ('quantidade_ocorrencias', models.PositiveIntegerField(help_text='Nº de itens defeituosos (P) ou total de defeitos (U)')),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostras_atributos', to='app.processo')),
            ],
        ),
    ]
