# Generated by Django 6.0.4 on 2026-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_processo_usar_regras_western'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_led_ligados', models.BooleanField(default=True, help_text='Se verdadeiro, o ESP32 acenderá os LEDs nos alertas')),
            ],
        ),
    ]
